### ISSUE TITLE
Optional Blacklist

### ISSUE THREAD

**Issue by bensnyde** [karolyi/py3-validate-email#29]
py3-validate-email cannot be pip installed without outbound network access since the setup.py fetches the domain blacklist file.

**Comment by karolyi** [comment]
yep, and pip fetches the package from the pypi repo.

**Comment by bensnyde** [comment]
Our enterprise uses Jfrog Artifactory to "securely" mirror packages from pypi. Our enterprise applications are allowed to pull from our internal Artifactory, but cannot breach the firewall to pull down the blocklist from Github. 

Would you be willing to use a skeleton blacklist file instead of forcing the download during setup?

**Comment by karolyi** [comment]
Can you post the complete error message you're getting when it tries to fetch the blacklist?

**Comment by karolyi** [comment]
Please try to post it with the version `0.2.10` which is out now with STARTTLS support.

**Comment by bensnyde** [comment]
I appreciate the update, but the problem is not with the SSL handshake.
Enterprise security frowns upon allowing an application to have egress
traffic, especially to a site like Github.

Since py3-validate-email forces a download of the blacklist from Github
during setup, we cannot use it, or any library that depends on it.

This is a request for a redesign wherein downloading the blacklist is
optional.

Perhaps instead of use_blacklist=True, you could accept a blacklist as a
parameter? Not only would this allow for greater configuration, but you
could set a default that would install/update your Github blacklist?

**Comment by karolyi** [comment]
Hey,

I knew the problem is not STARTTLS. I just asked you to post a detailed error log for me to see a traceback where the underlying updater throws an exception.

The generic idea is useful, I can of course change the source to make the downloading of the blacklist optional. But first, in order to fix it, I need to be able to reproduce the problem.

Secondly, this project is opensource, and so PRs are welcome. I can do it too, but right now I have other priorities: projects that are actually bringing some income. Right now I'm only available to this project in my most valued free time.
