### ISSUE TITLE
[enhancement] Use real email account and Port 465/587

### ISSUE THREAD

**Issue by fbarbier** [karolyi/py3-validate-email#59]
Hi,

Most email providers reject Port 25 now.
It would be a nice enhancement to be able to test email by using secure SMTP Connection (eg : Port 465 or 587).
It's also mean to be able to use a real email account and providing user+password (so extend py3-validate-email SMTP part).
For exemple, i like to use a gmail account to test emails.

**Comment by karolyi** [comment]
Port 25: Not true.

For port 465 and 587, see https://github.com/karolyi/py3-validate-email/issues/19#issuecomment-645339521

**Comment by reinhard-mueller** [comment]
Since this has repeatedly come up, we might consider adding something about this to the FAQ.

**Comment by fbarbier** [comment]
Could it be possible to add the ability to chose the SMTP port we wants to use (eg: 25, 465, 587) ?
Ability to use something like : helo_host_port=587 would be great (we can keep port 25 as default).

Agree with your comment, should word with port 25, but as today if I check email only 587 is working (smtp.gmail.com, smtp.outlook.com). In my test no need to connect with login/password, but i can't use port 25 for relay.

**Comment by reinhard-mueller** [comment]
I think you completely misunderstand the function of this library. It is not possible to use an SMTP relay server for the checks this library does. This library directly talks to the receiving mail server (the mail server which belongs to the email address you want to check).

**Comment by fbarbier** [comment]
No, I understand that this library talk directly to the receiving mail server, I just say you can't anymore talk with port 25, most mail providers require port 587.

If I try :

import smtplib

try:
    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.ehlo()
    server.starttls()
except:
    print 'Something went wrong...'

Everything good, but using port 25 doesn't work.

ps : sorry for the misunderstanding with the Relay part of my previous question.

**Comment by karolyi** [comment]
You can't talk to port 25 since it's blocked by your provider. It is not a general truth as you try to convey here. If port 25 would be blocked throughout the internet, the complete email system would break down.

Please stop spreading misinformation. As I stated before in the linked comment above, port 25 is used by SMTP implementations for *incoming* email delivery. Port 587 - as stands in its name - is for submission, that is for *outbound* emails. No implementation should use that port for inbound email delivery, and I don't know one that would support it. If they do, that is non standard and unsupported, and is a misconfiguration. The same goes with port 465, an implicit TLS version of port 587. They speak SMTP, but you have to authenticate with them in order to send *outbound* emails. Go dive into the closed issues on here and read more about it if you don't want to read the respective RFCs itselves.

Just because gmail might support your usecase (which is not proven so might be false information completely), it is NOT and SHOULD NOT be the case. Google does their own things, but they don't control the internet, contrary to popular belief.

Since this library is opensource, you can pervert it to your heart's liking but we're not gonna change it to support something that is not a standard.

With this said, this issue remains closed.

**Comment by fbarbier** [comment]
I wasn't asking to pervert your library, just to add an option for specific use cases. Sorry, if I gave false information .
Anyway, I like your library, and happy your share this with us.
Best

**Comment by reinhard-mueller** [comment]
@fbarbier side note just in case this helps you: you try the wrong server. smtp.gmail.com is *not* the server usable to verify the validity of something@gmail.com addresses. Try `host -t mx` to see a list of the correct servers. And these are also the servers that py3-validate-email will talk to.
