### ISSUE TITLE
Question , On IP being blacklisted

### ISSUE THREAD

**Issue by Bharadwajharii** [karolyi/py3-validate-email#69]
I am using the tool to validate a few  number of emails on a day to day basis.

Not too many , but I fear my IP may be blacklisted

Will the program produce output if I use a blacklisted IP. Any error or will the program not work

Also What is the recommended threshold on the number of email validations if any

**Comment by karolyi** [comment]
the output you'll get is that all your checks will fail.

if you use the `validate_email_or_fail`, you can look for the info in the exceptions, some mail servers disclose the fact that your IP is blocked based on blocklists. others don't. there's no simple rule to go by here because mailserver implementations and configurations vary.

exactly because of this, there is no recommended threshold on the usage of this module.

we should add this to the FAQ, if it's not already there.
